name: Develop Deploy

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Zip Project
      id: zip-project
      run: zip -r deploy.zip .

    - name: Get Commit Hash
      id: version-hash
      run: |
        echo "::set-output name=hash::${GITHUB_SHA}"

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v10
      with:
        aws_access_key: ${{ secrets.AWS_IAM_KEY_DEVELOP }}
        aws_secret_key: ${{ secrets.AWS_IAM_SECRET_DEVELOP }}
        application_name: ${{ secrets.AWS_EB_APP_DEVELOP }}
        environment_name: ${{ secrets.AWS_EB_ENV_DEVELOP }}
        version_label: ${{ steps.version-hash.outputs.hash }}
        region: ${{ secrets.AWS_REGION_DEVELOP }}
        deployment_package: deploy.zip
      
    - name: Slack Notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,commit,action,eventName,workflow
        author_name: ArenaOps
      env:
        SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
      if: always()
